name: Run Python Script and Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  schedule:
    # This schedule runs the workflow every day at midnight UTC.
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows you to trigger the workflow manually.

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository.
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Python.
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Cache pip dependencies to avoid reinstalling them every time.
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          # This caches the pip cache directory.
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install required dependencies.
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run your Python script that generates the HTML file.
      - name: Run Python Script
        run: python main.py  # Update the path to your script.
        
      # Step 6: Commit and push the generated HTML file to the repository so the github pages will update.
      - name: Commit and Push HTML File
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update index.html [skip ci]" || echo "No changes to commit"
          git push
