name: Run Python Script and Deploy to GitHub Pages

on:
  schedule:
    # This schedule runs the workflow every day at midnight UTC.
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows you to trigger the workflow manually.

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository.
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Python.
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Cache pip dependencies to avoid reinstalling them every time.
      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          # This caches the pip cache directory.
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install required dependencies.
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run your Python script that generates the HTML file.
      - name: Run Python Script
        run: python main.py  # Update the path to your script.

      # Step 6: Deploy the generated HTML file to GitHub Pages.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Set publish_dir to the directory where your HTML file is generated.
          publish_dir: index.html
